### ISSUE TITLE
Photo Model

### ISSUE THREAD

**Issue by GabeSArn** [samirdhebar/photo-sharing-app#11]
# Photo Model

Photos are a staple of the app. Users will be able to upload, and delete their own photos. Users will also be able to like, view, and comment on other users photos. 

### Attributes
1. Includes an integer, primary key which also auto increments as its id
2. Will include a timestamp for when the date was uploaded (TIMESTAMP)
3. Photos can have descriptions from the user (not necessary)
4. Can be edited or deleted by the user

### Relationships
- Photos have multiple comments (one to many)
- Photos have multiple likes (one to many)
- Photos can have only one user (one to one)
- Photos can (optional) have one description (one to one)

**Comment by samirdhebar** [comment]
Added "one to many/one" clarification on relationships.

Added additional detail on attributes (integer, primary key, auto incrementing etc).
