### ISSUE TITLE
Comments Model

### ISSUE THREAD

**Issue by GabeSArn** [samirdhebar/photo-sharing-app#13]
# Comments Model

Comments are user interactions with a posted photo. They will be left by other users, but can also be left by the user that uploaded the photo.

### Attributes

1. Includes an integer, primary key which also auto increments as its id
2. Is a string with a max length of (VARCHAR) 200 and is not null
3. Users can leave multiple comments on one photo

### Relationships
- Comments can have one user (one to many)
- Comments can have many likes (one to many)
- Comments can have dates (one to one)

**Comment by samirdhebar** [comment]
Added additional detail on attributes.
