### ISSUE TITLE
Set up models

### ISSUE THREAD

**Issue by samirdhebar** [samirdhebar/photo-sharing-app#9]

**Comment by GabeSArn** [comment]
We need to create and explain what our models will do. For example, our Users model should have the following attributes:

- Usernames
- Passwords
- Profile Pictures

**Comment by wbobeirne** [comment]
Can you break this out in to an issue _per model_? Ideally model issues can be defined like:

> # Name of Model
> _Short description of what the model is_
>
> * Attribute one (integer, primary key, auto increment)
> * Attribute two (String, max length 100, not null)
> * Attribute three (Text)
>
> Model has a one to many relationship with Other Model
> Model has a many to many relationship with Yet Another Model

**Comment by GabeSArn** [comment]
Got it.
